---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: nextgenconnect
spec: {}
status: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-mirth
  namespace: nextgenconnect
  labels:
    app: mysql
type: kubernetes.io/basic-auth
stringData:
  username: mirth
  password: M!rth53cr3t
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-root
  namespace: nextgenconnect
  labels:
    app: mysql
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: sUp3R53cr3T!
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: mysql
    run: mysql
  name: mysql
  namespace: nextgenconnect
spec:
  containers:
  - image: mysql:8.0
    name: mysql
    ports:
    - containerPort: 3306
    resources: {}
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret-root
          key: password
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysql-secret-mirth
          key: username
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret-mirth
          key: password
    - name: MYSQL_DATABASE
      value: mirthdb
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
  namespace: nextgenconnect
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextgenconnect-pvc
  labels:
    app: nextgenconnect
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextgenconnect
  namespace: nextgenconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextgenconnect
  template:
    metadata:
      labels:
        app: nextgenconnect
    spec:
      containers:
      - name: nextgenconnect
        image: docker.io/nextgenhealthcare/connect:3.12
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        - name: hl7-test
          containerPort: 9001
        env:
          - name: DATABASE
            value: mysql
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret-mirth
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret-mirth
                key: password
          - name: DATABASE_URL
            value: jdbc:mysql://mysql:3306/mirthdb
          - name: DATABASE_MAX_CONNECTIONS
            value: "20"
          - name: VMOPTIONS
            value: -Xmx512m
          - name: ALLOW_INSECURE
            value: "true"
          - name: DATABASE_MAX_RETRY
            value: "2"
          - name: DATABASE_MAX_RETRY_WAIT
            value: "10000"
        volumeMounts:
        - mountPath: /opt/connect/appdata
          name: nextgenconnect-pvc
      volumes:
      - name: nextgenconnect-pvc
        persistentVolumeClaim:
          claimName: nextgenconnect-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextgenconnect
  namespace: nextgenconnect
spec:
  type: LoadBalancer
  selector:
    app: nextgenconnect
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: hl7-test
      port: 9001
      targetPort: 9001
      protocol: TCP
