apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-root
  namespace: nextgenconnect
  labels:
    app: mysql
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: sUp3R53cr3T!
