apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-mirth
  namespace: nextgenconnect
  labels:
    app: mysql
type: kubernetes.io/basic-auth
stringData:
  username: mirth
  password: M!rth53cr3t
