apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
  namespace: nextgenconnect
spec:
  containers:
  - image: mysql:5.7
    name: mysql
    ports:
    - containerPort: 3306
    resources: {}
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret-root
          key: password
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysql-secret-mirth
          key: username
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret-mirth
          key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
