apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextgenconnect
  namespace: nextgenconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextgenconnect
  template:
    metadata:
      labels:
        app: nextgenconnect
    spec:
      initContainers:
      - name: mysql-init
        image: mysql:5.7
        command: 
        - bash
        - "-c"
        - |
          for i in {1..60}; 
            do sleep 1
            if mysql -h mysql-0.mysql -u root -e 'SELECT 1;'; then 
              mysql -h mysql-0.mysql -u root -e "CREATE USER IF NOT EXISTS '$DATABASE_USERNAME'@'%' IDENTIFIED BY '$DATABASE_PASSWORD'; GRANT ALL ON mirth_db.* TO '$DATABASE_USERNAME'@'%';"
              exit 0
            fi
          done
          exit 1
        env:
          - name: DATABASE
            value: mysql
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret-mirth
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret-mirth
                key: password
      containers:
      - name: nextgenconnect
        image: docker.io/nextgenhealthcare/connect
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        - name: hl7-test
          containerPort: 9001
        env:
          - name: DATABASE
            value: mysql
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret-mirth
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret-mirth
                key: password
          - name: DATABASE_URL
            value: jdbc:mysql://mysql-0.mysql:3306/mirth_db
          - name: DATABASE_MAX_CONNECTIONS
            value: "20"
          - name: VMOPTIONS
            value: -Xmx512m
