apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextgenconnect
  namespace: nextgenconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextgenconnect
  template:
    metadata:
      labels:
        app: nextgenconnect
    spec:
      containers:
      - name: nextgenconnect
        image: docker.io/nextgenhealthcare/connect
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        - name: hl7-test
          containerPort: 9001
        env:
          - name: DATABASE
            value: mysql
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret-mirth
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret-mirth
                key: password
          - name: DATABASE_URL
            value: jdbc:mysql://mysql:3306/mirthdb
          - name: DATABASE_MAX_CONNECTIONS
            value: "20"
          - name: VMOPTIONS
            value: -Xmx512m
          - name: ALLOW_INSECURE
            value: "true"
          - name: DATABASE_MAX_RETRY
            value: "2"
          - name: DATABASE_MAX_CONNECTIONS
            value: "20"
          - name: DATABASE_MAX_RETRY_WAIT
            value: "10000"
          - name: KEYSTORE_STOREPASS
            value: "changeme"
          - name: KEYSTORE_KEYPASS
            value: "changeme"
