apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextgenconnect-pvc
  labels:
    app: nextgenconnect
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
